### ISSUE TITLE
Auto healing for 1.51

### ISSUE THREAD

**Issue by Toonigy** [XPMUser/Website-Tester#14]
### What would you like to add?

Pde1500 had auto heal so why not for pde 1.51?

### Type of suggestion

A new Prodigy Definitive Edition (open-source), Prodigy Ultimate Edition, and/or Prodidows feature

### I agree to the following

- [X] By checking this box, I confirm that this issue's valid.
- [X] By checking this box, I confirm that I haven't already made an issue about the topic being presented in this issue.
- [X] By checking this box, I confirm that this issue template is being used to suggest a feature, not report a bug, and that if I want to make a bug report, I should not be using this issue template.

**Comment by XPMUser** [comment]
I'll try another time.
