### ISSUE TITLE
New version: 1.28.0.8

### ISSUE THREAD

**Issue by Toonigy** [XPMUser/Website-Tester#5]
### What would you like to add?

version 1.28.0.8

### Type of suggestion

A new Prodigy Definitive Edition (open-source), Prodigy Ultimate Edition, and/or Prodidows feature

### I agree to the following

- [X] By checking this box, I confirm that this issue's valid.
- [X] By checking this box, I confirm that I haven't already made an issue about the topic being presented in this issue.
- [x] By checking this box, I confirm that this issue template is being used to suggest a feature, not report a bug, and that if I want to make a bug report, I should not be using this issue template.

**Comment by XPMUser** [comment]
1.28.0.8 isn't Definitive Edition, Ultimate Edition, or Prodidows.
