### ISSUE TITLE
Old ui in 1.51 like in 1.50

### ISSUE THREAD

**Issue by Toonigy** [XPMUser/Website-Tester#7]
### What would you like to add?

Make 1.51 definitive have the orange ui too

### Type of suggestion

A new Prodigy Definitive Edition (open-source), Prodigy Ultimate Edition, and/or Prodidows feature

### I agree to the following

- [X] By checking this box, I confirm that this issue's valid.
- [X] By checking this box, I confirm that I haven't already made an issue about the topic being presented in this issue.
- [X] By checking this box, I confirm that this issue template is being used to suggest a feature, not report a bug, and that if I want to make a bug report, I should not be using this issue template.

**Comment by XPMUser** [comment]
Coming Soon
